# Generated by Django 3.2.7 on 2021-10-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='message_group_id',
            field=models.PositiveIntegerField(default=-1, verbose_name='Message group ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegrampoll',
            name='poll_group_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Poll group id'),
            preserve_default=False,
        ),
    ]
