# Generated by Django 3.2.7 on 2021-10-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrampoll',
            name='options_text',
            field=models.JSONField(default=[], verbose_name='Options text'),
            preserve_default=False,
        ),
    ]
