# Generated by Django 3.2.7 on 2021-10-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0002_auto_20211005_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='message_group_id',
            field=models.TextField(verbose_name='Message group ID'),
        ),
        migrations.AlterField(
            model_name='telegrampoll',
            name='poll_group_id',
            field=models.TextField(verbose_name='Poll group id'),
        ),
    ]
