# Generated by Django 3.2.7 on 2021-10-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0003_auto_20211005_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='telegram_message_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='Telegram message ID'),
        ),
        migrations.AlterField(
            model_name='telegrampoll',
            name='poll_group_id',
            field=models.PositiveBigIntegerField(verbose_name='Poll group id'),
        ),
    ]
