# Generated by Django 3.2.7 on 2021-10-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0003_auto_20211019_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='telegram_username',
        ),
    ]
