# Generated by Django 3.2.7 on 2021-10-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0004_auto_20211005_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrampoll',
            name='telegram_message_id',
            field=models.PositiveBigIntegerField(default=0, unique=True, verbose_name='Telegram message ID'),
            preserve_default=False,
        ),
    ]
