# Generated by Django 3.2.7 on 2021-10-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0005_telegrampoll_telegram_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='text',
            field=models.TextField(default='', verbose_name='Message text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegrampoll',
            name='question',
            field=models.TextField(default='', verbose_name='Poll question'),
            preserve_default=False,
        ),
    ]
