# Generated by Django 3.2.7 on 2021-10-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0006_auto_20211005_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrampoll',
            name='selected_options',
            field=models.JSONField(null=True, verbose_name='Selected options by student'),
        ),
    ]
