# Generated by Django 3.2.7 on 2021-10-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0007_telegrampoll_selected_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrampoll',
            name='option_number',
            field=models.PositiveIntegerField(default=2, verbose_name='Option number'),
            preserve_default=False,
        ),
    ]
