# Generated by Django 3.2.7 on 2021-10-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0008_telegrampoll_option_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='answer',
            field=models.TextField(null=True, verbose_name='Question answer'),
        ),
    ]
