# Generated by Django 3.2.7 on 2021-10-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0009_telegrammessage_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='message_group_id',
            field=models.PositiveBigIntegerField(verbose_name='Message group ID'),
        ),
    ]
