# Generated by Django 3.2.7 on 2021-10-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0010_alter_telegrammessage_message_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Is question closed'),
            preserve_default=False,
        ),
    ]
