# Generated by Django 3.2.7 on 2021-10-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0011_telegrammessage_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrampoll',
            name='is_manually_closed',
            field=models.BooleanField(default=False, verbose_name='Is poll manually closed'),
        ),
        migrations.AddField(
            model_name='telegrampoll',
            name='open_period',
            field=models.DateTimeField(null=True, verbose_name='Open period'),
        ),
    ]
