# Generated by Django 3.2.7 on 2021-10-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0012_auto_20211011_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrampoll',
            name='open_period',
            field=models.PositiveIntegerField(null=True, verbose_name='Open period'),
        ),
    ]
