# Generated by Django 3.2.7 on 2021-10-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0013_alter_telegrampoll_open_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='image_answer',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image answer'),
        ),
    ]
