# Generated by Django 3.2.7 on 2021-10-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0015_auto_20211011_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrammessage',
            name='image_id_answer',
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='image_ids',
            field=models.JSONField(null=True, verbose_name='Image answer IDs'),
        ),
    ]
